[build]
target = "riscv32imac-unknown-none-elf"

[target.riscv32imac-unknown-none-elf]
runner = "wlink -v flash --enable-sdi-print --watch-serial"
# runner = "wlink -v flash --no-erase --dry-run"

rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]
